spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/preppydb
    host: postgres
    password:

---

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    host: postgres
    password: ${DB_PASS}

